# HTTP to HTTPS redirect (if using this block)
# server {
#     listen 8080;
#     server_name localhost;

#     # Redirect all HTTP requests to HTTPS
#     return 301 https://$host$request_uri;
# }

# HTTPS server block
server {
    # listen 8080 default_server ssl;
    listen 8080;
    server_name localhost;

    # SSL certificate and key
    # ssl_certificate /etc/nginx/ssl/ssl-certif.crt;
    # ssl_certificate_key /etc/nginx/ssl/private.key;

    # ssl_protocols TLSv1.2 TLSv1.3;
    # ssl_prefer_server_ciphers on;

    # Headers for proxying
    location / {
        proxy_pass http://matcha:3000;  # Proxy to the matcha service

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        # proxy_set_header X-Forwarded-Proto https;  # Ensure it's treated as https
        # proxy_set_header X-Forwarded-Host $host;  # Forward the correct host (localhost)
        # proxy_set_header X-Forwarded-Port 8080;  # Ensure the correct port is forwarded
		proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    # Socket.io location
    location /socket.io {
        proxy_max_temp_file_size 8192m;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
        proxy_pass http://matcha:3000;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
		proxy_set_header X-Forwarded-Proto $scheme;
        # proxy_set_header X-Forwarded-Proto https;
        # proxy_set_header X-Forwarded-Host $host;
        # proxy_set_header X-Forwarded-Port 8080;

        proxy_redirect off;
    }
}
