services:
  matcha:
    image: matcha-sveltkit
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: matcha-sveltkit
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
